### ISSUE TITLE
Please respect code license

### ISSUE THREAD

**Issue by urish** [synap-ai/eeg-explorer#9]
Hi, 

Nice to see the project evolving! 

Please note that the original code was released under the [MIT License](https://opensource.org/licenses/MIT), which means the original Copyright notice shall be included in this derivative work. However, one of your [recent commits](https://github.com/synap-ai/eeg-explorer/commit/290f28300db2b8e29cbf80089f4b7ed0e450a752) has removed this copyright notice. @alexcastillo and I spent a substantial amount of time on this project, and we hope that you can respect that.

**Comment by hnrytrn** [comment]
Sorry about that, I didn't mean to remove the MIT License. I added back in here https://github.com/synap-ai/eeg-explorer/commit/e14cf1298b5532881bcee9bdd7203999b0e6ce36.

**Comment by urish** [comment]
Lovely, thank you! 😍
